# # senha padrao do seleniumhub é :secret
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    ports:
      - "1433:1433"
    volumes:
    - dbdata:/var/opt/mssql
    environment:
      MSSQL_TCP_PORT: 1433
      MSSQL_SA_PASSWORD: "P@55w0rd"
      ACCEPT_EULA: "Y"
    networks:
      - WakeCommerceNetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - WakeCommerceNetwork

networks:
  WakeCommerceNetwork:
    driver: bridge
    
volumes:  
  dbdata:
  redis-data:
    driver: local