# # senha padrao do seleniumhub é :secret
services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: database
    ports:
      - "1433:1433"
    volumes:
    - dbdata:/var/opt/mssql
    environment:
      MSSQL_TCP_PORT: 1433
      MSSQL_SA_PASSWORD: "P@55w0rd"
      ACCEPT_EULA: "Y"
    networks:
      - WakeCommerceNetwork
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "P@55w0rd", "-Q", "SELECT 1"]
      interval: 10s  # Checa a cada 10 segundos
      timeout: 5s     # Aguarda até 5s pela resposta
      retries: 5      # Tenta 5 vezes antes de considerar como "não saudável"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - WakeCommerceNetwork

  wakecommerce-webapi:
    container_name: WakeCommerce-WebApi
    depends_on:
      - database
      - redis
    build: 
      context: .
    environment:
      - ENVIRONMENT_NAME=Test
      - ASPNETCORE_ENVIRONMENT=Test
    ports:
      - "5000:8081"
      - "5001:8080"
    networks:
      - WakeCommerceNetwork

networks:
  WakeCommerceNetwork:
    driver: bridge
    
volumes:  
  dbdata:
  redis-data:
    driver: local