apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: wakecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest  
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "P@55w0rd"  
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserver-storage
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: sqlserver-pvc
