apiVersion: v1
kind: Namespace
metadata:
  name:  wakecommerce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-server
  namespace: wakecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        ports:
        - containerPort: 3100
        - containerPort: 9095
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/loki-config.yaml
          subPath: loki-config.yaml
        - name: loki-storage
          mountPath: /loki
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}
