apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: wakecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472  # O ID do grupo do Grafana, ajuste conforme necessário
      containers:
        - name: grafana
          image: grafana/grafana:latest
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-storage
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: admin-password
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc


